class NotFoundRecordError(Exception):
    pass


class AlreadyExistError(Exception):
    pass